version: '3'

services:
    mysqldb:
        container_name: mysqldb
        image: mysql:latest
        cap_add:
        - SYS_NICE
        environment:
        - MYSQL_ROOT_PASSWORD=password
        volumes:
        - ./init:/docker-entrypoint-initdb.d
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
    process_routine:
        container_name: process_routine
        build:
            context: .
        volumes:
            - .:/app
        ports:
        - 3000:5000
        depends_on:
            - mysqldb

volumes:
    mysqlVolume:
    mysqlConfig: